# Generated by Django 3.2.16 on 2022-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221205_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mod_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
